variables:
  major: 1
  minor: 0
  patch: $[counter(format('major {0} minor {1}', variables['major'], variables['minor']), 0)]

name: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]

resources:
  - repo: self
    clean: true

trigger:
  - master

steps:
  - task: Npm@1
    inputs:
      command: 'ci'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'test'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'version $(Build.BuildNumber) --no-git-tag-version'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'publish'
