variables:
  prbuildnumber: $[counter('pr', 1)]

name: $[format('PR - {0}', variables['prbuildnumber'])]

resources:
  - repo: self
    clean: true

trigger: none

pr:
  - master

steps:
  - task: Npm@1
    inputs:
      command: 'ci'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'test'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'